// Plan FIT · 31 días — datos de entrenamiento
// type: fuerza | core | hiit | cardio | descanso | test | reto
const WARMUP = {
  title: "Calentamiento (2 min)",
  items: [
    "30 s jumping jacks",
    "30 s movilidad de hombros",
    "30 s movilidad de cadera",
    "30 s sentadillas suaves",
  ],
};

const WORKOUTS = [
  {
    day: 1, week: 1, type: "fuerza",
    title: "Fuerza tren superior + piernas",
    format: "3 rondas", rounds: 3,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Flexiones", reps: 10, scale: "De rodillas si hace falta" },
      { name: "Sentadillas", reps: 15 },
      { name: "Zancadas (por lado)", reps: 10 },
      { name: "Mountain climbers", reps: 20 },
      { name: "Plancha", seconds: 30 },
    ],
  },
  {
    day: 2, week: 1, type: "hiit",
    title: "HIIT cardio",
    format: "5 rondas · intervalos", rounds: 5,
    restBetweenRounds: 60,
    exercises: [
      { name: "Jumping jacks", seconds: 45, restAfter: 15 },
      { name: "Burpees", seconds: 45, restAfter: 15, scale: "Sin salto si hace falta" },
      { name: "Rodillas arriba (high knees)", seconds: 45, restAfter: 15 },
      { name: "Mountain climbers", seconds: 45 },
    ],
  },
  {
    day: 3, week: 1, type: "core",
    title: "Core",
    format: "3 rondas", rounds: 3,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Plancha", seconds: 40 },
      { name: "Crunches", reps: 20 },
      { name: "Elevaciones de piernas", reps: 15 },
      { name: "Russian twist", reps: 20 },
      { name: "Plancha lateral (por lado)", seconds: 30 },
    ],
  },
  {
    day: 4, week: 1, type: "fuerza",
    title: "Piernas",
    format: "3 rondas", rounds: 3,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Sentadillas", reps: 20 },
      { name: "Sentadillas con salto", reps: 15, scale: "Sin salto si hace falta" },
      { name: "Zancadas (por lado)", reps: 12 },
      { name: "Wall sit", seconds: 45 },
    ],
  },
  {
    day: 5, week: 1, type: "fuerza",
    title: "Full body",
    format: "3 rondas", rounds: 3,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Flexiones", reps: 12, scale: "De rodillas si hace falta" },
      { name: "Burpees", reps: 15, scale: "Sin salto si hace falta" },
      { name: "Sentadillas", reps: 20 },
      { name: "Mountain climbers", reps: 20 },
      { name: "Plancha", seconds: 40 },
    ],
  },
  {
    day: 6, week: 1, type: "cardio",
    title: "Cardio en intervalos",
    format: "20 min · 1' trote + 1' rápido ×10",
    exercises: [
      { name: "Trote suave", seconds: 60, repeatLabel: "×10" },
      { name: "Ritmo rápido", seconds: 60, repeatLabel: "×10" },
    ],
    tip: "Alterna 1 minuto suave y 1 minuto rápido durante 20 minutos seguidos.",
  },
  {
    day: 7, week: 1, type: "descanso",
    title: "Descanso activo",
    format: "30 min caminar + 10 min estiramientos",
    exercises: [
      { name: "Caminar a ritmo suave", seconds: 1800 },
      { name: "Estiramientos generales", seconds: 600 },
    ],
  },

  {
    day: 8, week: 2, type: "fuerza",
    title: "Fuerza tren superior + piernas",
    format: "4 rondas", rounds: 4,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Flexiones", reps: 12, scale: "De rodillas si hace falta" },
      { name: "Sentadillas", reps: 20 },
      { name: "Zancadas (por lado)", reps: 12 },
      { name: "Mountain climbers", reps: 20 },
      { name: "Plancha", seconds: 45 },
    ],
  },
  {
    day: 9, week: 2, type: "hiit",
    title: "HIIT cardio",
    format: "6 rondas · intervalos", rounds: 6,
    restBetweenRounds: 60,
    exercises: [
      { name: "Burpees", seconds: 40, restAfter: 20, scale: "Sin salto si hace falta" },
      { name: "Mountain climbers", seconds: 40, restAfter: 20 },
      { name: "Jumping jacks", seconds: 40 },
    ],
  },
  {
    day: 10, week: 2, type: "core",
    title: "Core",
    format: "4 rondas", rounds: 4,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Crunches", reps: 25 },
      { name: "Elevaciones de piernas", reps: 20 },
      { name: "Russian twist", reps: 30 },
      { name: "Plancha", seconds: 45 },
      { name: "Plancha lateral (por lado)", seconds: 35 },
    ],
  },
  {
    day: 11, week: 2, type: "fuerza",
    title: "Piernas",
    format: "4 rondas", rounds: 4,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Sentadillas", reps: 20 },
      { name: "Sentadillas con salto", reps: 20, scale: "Sin salto si hace falta" },
      { name: "Zancadas (por lado)", reps: 15 },
      { name: "Wall sit", seconds: 60 },
    ],
  },
  {
    day: 12, week: 2, type: "hiit",
    title: "AMRAP",
    format: "AMRAP 15 min", amrapMinutes: 15,
    exercises: [
      { name: "Burpees", reps: 8, scale: "Sin salto si hace falta" },
      { name: "Flexiones", reps: 10, scale: "De rodillas si hace falta" },
      { name: "Sentadillas", reps: 15 },
      { name: "Mountain climbers", reps: 20 },
    ],
    tip: "Encadena todas las rondas que puedas en 15 minutos sin parar el crono.",
  },
  {
    day: 13, week: 2, type: "hiit",
    title: "HIIT cardio",
    format: "5 rondas · intervalos", rounds: 5,
    restBetweenRounds: 60,
    exercises: [
      { name: "Burpees", seconds: 45, restAfter: 15, scale: "Sin salto si hace falta" },
      { name: "Rodillas arriba (high knees)", seconds: 45, restAfter: 15 },
      { name: "Jumping jacks", seconds: 45, restAfter: 15 },
      { name: "Mountain climbers", seconds: 45 },
    ],
  },
  {
    day: 14, week: 2, type: "descanso",
    title: "Descanso activo",
    format: "30 min caminar + movilidad",
    exercises: [
      { name: "Caminar a ritmo suave", seconds: 1800 },
      { name: "Movilidad articular", seconds: 300 },
    ],
  },

  {
    day: 15, week: 3, type: "fuerza",
    title: "Fuerza tren superior + piernas",
    format: "4 rondas", rounds: 4,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Flexiones", reps: 15, scale: "De rodillas si hace falta" },
      { name: "Sentadillas", reps: 20 },
      { name: "Zancadas (por lado)", reps: 15 },
      { name: "Mountain climbers", reps: 25 },
      { name: "Plancha", seconds: 60 },
    ],
  },
  {
    day: 16, week: 3, type: "hiit",
    title: "EMOM",
    format: "EMOM 15 min", emomMinutes: 15,
    exercises: [
      { name: "Burpees", reps: 8, scale: "Sin salto si hace falta" },
      { name: "Flexiones", reps: 8, scale: "De rodillas si hace falta" },
      { name: "Sentadillas", reps: 12 },
    ],
    tip: "Cada minuto en punto haz los 3 ejercicios seguidos; descansa lo que sobre del minuto.",
  },
  {
    day: 17, week: 3, type: "core",
    title: "Core",
    format: "4 rondas", rounds: 4,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Plancha", seconds: 60 },
      { name: "Crunches", reps: 30 },
      { name: "Elevaciones de piernas", reps: 20 },
      { name: "Russian twist", reps: 30 },
      { name: "Bicycle crunches", reps: 20 },
    ],
  },
  {
    day: 18, week: 3, type: "fuerza",
    title: "Piernas",
    format: "4 rondas", rounds: 4,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Sentadillas", reps: 25 },
      { name: "Sentadillas con salto", reps: 20, scale: "Sin salto si hace falta" },
      { name: "Zancadas (por lado)", reps: 15 },
      { name: "Wall sit", seconds: 60 },
    ],
  },
  {
    day: 19, week: 3, type: "hiit",
    title: "AMRAP",
    format: "AMRAP 18 min", amrapMinutes: 18,
    exercises: [
      { name: "Flexiones", reps: 10, scale: "De rodillas si hace falta" },
      { name: "Burpees", reps: 15, scale: "Sin salto si hace falta" },
      { name: "Sentadillas", reps: 20 },
      { name: "Mountain climbers", reps: 20 },
      { name: "Plancha", seconds: 30 },
    ],
    tip: "Encadena todas las rondas que puedas en 18 minutos sin parar el crono.",
  },
  {
    day: 20, week: 3, type: "cardio",
    title: "Cardio en intervalos",
    format: "20 min · 1' rápido + 1' suave ×10",
    exercises: [
      { name: "Ritmo rápido", seconds: 60, repeatLabel: "×10" },
      { name: "Ritmo suave", seconds: 60, repeatLabel: "×10" },
    ],
    tip: "Alterna 1 minuto rápido y 1 minuto suave durante 20 minutos seguidos.",
  },
  {
    day: 21, week: 3, type: "descanso",
    title: "Descanso activo",
    format: "30 min caminar + 10 min movilidad",
    exercises: [
      { name: "Caminar a ritmo suave", seconds: 1800 },
      { name: "Movilidad articular", seconds: 600 },
    ],
  },

  {
    day: 22, week: 4, type: "fuerza",
    title: "Fuerza tren superior + piernas",
    format: "5 rondas", rounds: 5,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Flexiones", reps: 15, scale: "De rodillas si hace falta" },
      { name: "Sentadillas", reps: 25 },
      { name: "Zancadas (por lado)", reps: 15 },
      { name: "Mountain climbers", reps: 30 },
      { name: "Plancha", seconds: 60 },
    ],
  },
  {
    day: 23, week: 4, type: "hiit",
    title: "HIIT cardio",
    format: "6 rondas · intervalos", rounds: 6,
    restBetweenRounds: 60,
    exercises: [
      { name: "Burpees", seconds: 40, restAfter: 20, scale: "Sin salto si hace falta" },
      { name: "Mountain climbers", seconds: 40, restAfter: 20 },
      { name: "Rodillas arriba (high knees)", seconds: 40, restAfter: 20 },
      { name: "Jumping jacks", seconds: 40 },
    ],
  },
  {
    day: 24, week: 4, type: "core",
    title: "Core",
    format: "5 rondas", rounds: 5,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Plancha", seconds: 60 },
      { name: "Crunches", reps: 30 },
      { name: "Elevaciones de piernas", reps: 25 },
      { name: "Russian twist", reps: 40 },
      { name: "Bicycle crunches", reps: 20 },
    ],
  },
  {
    day: 25, week: 4, type: "fuerza",
    title: "Piernas",
    format: "5 rondas", rounds: 5,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Sentadillas", reps: 25 },
      { name: "Sentadillas con salto", reps: 20, scale: "Sin salto si hace falta" },
      { name: "Zancadas (por lado)", reps: 20 },
      { name: "Wall sit", seconds: 60 },
    ],
  },
  {
    day: 26, week: 4, type: "hiit",
    title: "AMRAP",
    format: "AMRAP 20 min", amrapMinutes: 20,
    exercises: [
      { name: "Burpees", reps: 10, scale: "Sin salto si hace falta" },
      { name: "Flexiones", reps: 15, scale: "De rodillas si hace falta" },
      { name: "Sentadillas", reps: 20 },
      { name: "Mountain climbers", reps: 30 },
      { name: "Plancha", seconds: 30 },
    ],
    tip: "Encadena todas las rondas que puedas en 20 minutos sin parar el crono.",
  },
  {
    day: 27, week: 4, type: "cardio",
    title: "Cardio continuo",
    format: "20 min ritmo continuo",
    exercises: [{ name: "Cardio continuo (trote, bici, elíptica...)", seconds: 1200 }],
  },
  {
    day: 28, week: 4, type: "descanso",
    title: "Movilidad y estiramientos",
    format: "20 min",
    exercises: [{ name: "Movilidad y estiramientos completos", seconds: 1200 }],
  },

  {
    day: 29, week: 5, type: "test",
    title: "Test de progreso",
    format: "Test cronometrado",
    exercises: [
      { name: "Máx. flexiones en 2 min", seconds: 120 },
      { name: "Máx. sentadillas en 2 min", seconds: 120 },
      { name: "Máx. burpees en 2 min", seconds: 120 },
      { name: "Plancha máxima (aguanta lo que puedas)", seconds: null },
      { name: "Carrera 2 km (cronometra el tiempo)", seconds: null },
    ],
    tip: "Apunta tus marcas: te sirven para comparar con el día 1 y ver tu progreso real.",
  },
  {
    day: 30, week: 5, type: "reto",
    title: "Military Challenge",
    format: "5 rondas", rounds: 5,
    restBetweenExercises: 20, restBetweenRounds: 60,
    exercises: [
      { name: "Burpees", reps: 10, scale: "Sin salto si hace falta" },
      { name: "Flexiones", reps: 15, scale: "De rodillas si hace falta" },
      { name: "Sentadillas", reps: 20 },
      { name: "Mountain climbers", reps: 20 },
      { name: "Zancadas (por lado)", reps: 15 },
      { name: "Plancha", seconds: 60 },
    ],
  },
  {
    day: 31, week: 5, type: "descanso",
    title: "Recuperación activa",
    format: "30 min caminar + estiramientos completos",
    exercises: [
      { name: "Caminar a ritmo suave", seconds: 1800 },
      { name: "Estiramientos completos", seconds: 600 },
    ],
    tip: "¡Enhorabuena por completar el plan! Aprovecha para comparar tus fotos/medidas con el día 1.",
  },
];

const TYPE_META = {
  fuerza:   { label: "Fuerza",   color: "#B4FF39" },
  core:     { label: "Core",     color: "#4AD9FF" },
  hiit:     { label: "HIIT",     color: "#FF6B4A" },
  cardio:   { label: "Cardio",   color: "#FFD23F" },
  descanso: { label: "Descanso", color: "#8B93A7" },
  test:     { label: "Test",     color: "#FF4AD1" },
  reto:     { label: "Reto",     color: "#FF2E2E" },
};
